### ISSUE TITLE
canAccessVideos Middleware Not Found

### ISSUE THREAD

**Issue by stephenjude** [spatie/laravel-beyond-crud.com#18]
This middleware `'canAccessVideos' => \App\Http\Middleware\CanAccessVideos::class,` was registered in the `kernel.php` but its nowhere to be found.

It's supposed to be here in the [middleware directory](https://github.com/spatie/laravel-beyond-crud.com/tree/master/app/Http/Middleware)

**Comment by freekmurze** [comment]
It's not used anymore, I've removed it.

**Comment by stephenjude** [comment]
Okay
